apiVersion: v1
kind: Pod
metadata:
  name: django-app
spec:
  containers:
    - name: django
      image: django_app_learn_kuber:1.0.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000