apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: django-app-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: django
          image: django_app_learn_kuber:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000